# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ec7906248eed7c537f7f961cf69eddfe75af00e670dc932b4514a2a66ed67a5995b19f932f3c88163ab3be03979ed1b8294106dd21fca9528c272d0000e45f0

test:
  secret_key_base: 9953d17badc8188d0b49163937ae0bcb107052b16d2028edae99480fe91c1d338b57eeca3e361b4bb1efb08615ec97e348c2ecfc8d35aca6fc2f0eb25adb3c40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
